apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: mahendra
spec:
  replicas: 3
  strategy: 
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: c1
        image: mahendrshinde/myweb:1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "32Mi"
            cpu: "150m"
          requests:
            memory: "16Mi"
            cpu: "50m"