apiVersion: v1
kind: ConfigMap
metadata:
  name: myappconfig
  namespace: mahendra
data:
  # Key-Value Pairs for Configuration
  # Injected inside the Pod as Environment Variables
  db_url: "jdbc:mysql://mysqlserver:3306/mydb"
  db_username: "root"
  db_password: "password"
  db_driver: "com.mysql.cj.jdbc.Driver"
---
apiVersion: v1
kind: Pod
metadata:
  name: app2
  namespace: mahendra
spec:
  containers:
  - name: c1
    image: mahendrshinde/myweb:1
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: myappconfig