apiVersion: v1
kind: Secret
metadata:
  name: myappsecret
  namespace: mahendra
data:
  # Generic Secret : Key-Value Pairs for Configuration
  # Injected inside the Pod as Environment Variables
  db_url: "amRiYzpteXNxbDovL215c3Fsc2VydmVyOjMzMDYvbXlkYgo="
  db_username: "cm9vdAo="
  db_password: "cGFzc3dvcmQK"
  db_driver: "Y29tLm15c3FsLmNqLmpkYmMuRHJpdmVyCg=="
---
apiVersion: v1
kind: Pod
metadata:
  name: app3
  namespace: mahendra
spec:
  containers:
  - name: c1
    image: mahendrshinde/myweb:1
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: myappsecret