apiVersion: v1
kind: Pod
metadata:
  name: app4
  namespace: mahendra
spec:
  imagePullSecrets:
  - name: regcred
  containers:
  - name: c1
    image: mahendrashinde.azurecr.io/myweb:1
    ports:
    - containerPort: 80