apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-db
spec:
  serviceName: db
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: sample
        - name: MYSQL_USER
          value: dbadmin
        - name: MYSQL_PASSWORD
          value: password1234
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: dbvol
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: dbvol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: mysql
  ports:  
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None  ### ClusterIP is None for headless service