apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: myapp
        image: mahendrshinde/library-api-az-insights
        resources:
          limits:
            memory: "2Gi"
            cpu: "500m"
          requests:
            memory: "1Gi"
            cpu: "100m"
        ports:
        - containerPort: 8080
